server:
  port: 8085
spring:
  application:
    name: ts-patient-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # URI of our Auth Service. The resource server will fetch public keys from here to validate tokens.
          issuer-uri: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/patients?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # A much more reasonable default
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Integration service URLs
integration:
  user-service:
    base-url: http://ts-user-service/api/v1/users
  address-service:
    base-url: http://ts-address-service/api/v1/addresses
  session-service:
    base-url: http://ts-schedule-service/api/v1/schedules

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      ts-user-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
      ts-address-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
      ts-schedule-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50

  retry:
    instances:
      ts-user-service:
        max-attempts: 3
        wait-duration: 1s
      ts-address-service:
        max-attempts: 3
        wait-duration: 1s
      ts-schedule-service:
        max-attempts: 3
        wait-duration: 1s

  timelimiter:
    instances:
      ts-user-service:
        timeout-duration: 10s
      ts-address-service:
        timeout-duration: 10s
      ts-schedule-service:
        timeout-duration: 10s
